name: Lint
on: push
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
          composer install
      - name: Lint
        run: composer lint
      - name: Test validator
        run: |
          # Initialize an empty string to collect errors
          VALIDATION_ERRORS=""
          echo "Testing good files..."
          # Loop through all files in the good fixtures directory and copy them to the src/data directory
          for file in ${{ github.workspace }}/.github/workflows/fixtures/good/*.json; do
            echo "Copying $file..."
            cp "$file" "${{ github.workspace }}/src/data/"
          done

          # Validate good files, expecting success
          if ! composer validate-files; then
            VALIDATION_ERRORS+="Validation failed for good input. "
          fi
          
          # Clean up after testing with valid files
          composer clean-files
          
          echo "Testing bad files..."
          # Setup for invalid files
          for file in ${{ github.workspace }}/.github/workflows/fixtures/bad/*.json; do
            echo "Copying $file..."
            cp "$file" "${{ github.workspace }}/src/data/"
          done

          # Validate bad files, expecting failure
          if composer validate-files; then
            # If the validation unexpectedly succeeds, add an error message
            VALIDATION_ERRORS+="Validation did not fail as expected for bad input. "
          else
            # If the validation fails as expected, this is the correct behavior, so do nothing or log as needed
            echo "Validation failed as expected for bad input."
          fi

          # Check if there were any validation errors
          if [ -n "$VALIDATION_ERRORS" ]; then
            echo "Errors during validation: $VALIDATION_ERRORS"
            exit 1
          else
            echo "All validations passed successfully."
          fi
