name: Autotag and Release
on:
  push:
    branches:   
      - main
jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pantheon-systems/action-autotag@v0.x
        with:
          gh-token: ${{ github.token }}